version: '3.8'

services:
  # Grafana - Visualization and dashboards
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - observability
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  # Mimir - Metrics storage
  mimir:
    image: grafana/mimir:2.11.0
    container_name: mimir
    ports:
      - "9009:9009"
    command: [
      "-config.file=/etc/mimir/mimir.yaml",
      "-target=all"
    ]
    volumes:
      - ./observability/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir-data:/data
    networks:
      - observability

  # Loki - Logs storage
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki/loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - observability

  # Tempo - Traces storage
  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - observability

  # Pyroscope - Continuous profiling
  pyroscope:
    image: grafana/pyroscope:1.4.0
    container_name: pyroscope
    ports:
      - "4040:4040"
    command:
      - "server"
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    volumes:
      - pyroscope-data:/data
    networks:
      - observability

  # Alloy - Observability data collector
  alloy:
    image: grafana/alloy:v1.0.0
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - --stability.level=generally-available
    environment:
      - ALLOY_DEPLOY_MODE=docker
    networks:
      - observability
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  # Application (commented out - run locally)
  # app:
  #   build: .
  #   container_name: observability-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
  #     - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://alloy:4318/v1/traces
  #     - MANAGEMENT_OTLP_METRICS_ENDPOINT=http://alloy:4318/v1/metrics
  #     - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
  #     - OTEL_SERVICE_NAME=observability-example
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=observability-example,service.version=1.0.0
  #   volumes:
  #     - app-logs:/app/logs
  #   networks:
  #     - observability
  #   depends_on:
  #     - alloy

volumes:
  grafana-storage:
  mimir-data:
  loki-data:
  tempo-data:
  pyroscope-data:
  app-logs:

networks:
  observability:
    driver: bridge
