version: '3.8'

services:
  # Grafana - Visualization and dashboards
  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=*
      - GF_PLUGINS_PLUGIN_ADMIN_ALLOW_LOADING_UNSIGNED_PLUGINS=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - observability
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  # Mimir - Metrics storage
  mimir:
    image: grafana/mimir:2.17.0
    container_name: mimir
    ports:
      - "9009:9009"
    command: [
      "-config.file=/etc/mimir/mimir.yaml",
      "-target=all"
    ]
    volumes:
      - ./observability/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir-data:/data
    networks:
      - observability

  # Loki - Logs storage
  loki:
    image: grafana/loki:3.5.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki/loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - observability

  # Tempo - Traces storage
  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    ports:
      - "3200:3200"   # tempo web ui
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
      - ./observability/tempo-data:/var/lib/tempo
    networks:
      - observability

  # Pyroscope - Continuous profiling
  pyroscope:
    image: grafana/pyroscope:1.14.1
    container_name: pyroscope
    ports:
      - "4040:4040"
    command:
      - "server"
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    volumes:
      - pyroscope-data:/data
    networks:
      - observability

  # Alloy - Observability data collector
  alloy:
    image: grafana/alloy:v1.10.2
    container_name: alloy
    ports:
      - "4041:4041"
      - "12345:12345"
      - "14317:14317"
      - "14318:14318"
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --stability.level=public-preview
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    environment:
      - ALLOY_DEPLOY_MODE=docker
    networks:
      - observability
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  # Application with sidecar instrumentation
  app:
    image: observability-example:latest
    container_name: observability-app
    ports:
      - "8080:8080"
      - "9464:9464"  # Prometheus metrics from OpenTelemetry agent
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - app-logs:/app/logs
    networks:
      - observability
    depends_on:
      - alloy

volumes:
  grafana-storage:
  mimir-data:
  loki-data:
  tempo-data:
  pyroscope-data:
  app-logs:

networks:
  observability:
    driver: bridge
