apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    uid: mimir
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      prometheusType: Mimir
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
      alertmanagerDatasource: tempo
      customQueryParameters: 'max_source_resolution=0s'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"trace_id\":\"([a-f0-9]+)\""
          name: Trace
          url: "/explore?orgId=1&left={\"datasource\":\"tempo\",\"queries\":[{\"query\":\"${__value.raw}\",\"queryType\":\"traceId\"}]}"
        - datasourceUid: pyroscope
          matcherRegex: "\"trace_id\":\"([a-f0-9]+)\""
          name: Profile
          url: "/explore?orgId=1&left={\"datasource\":\"pyroscope\",\"queries\":[{\"query\":\"service_name=observability-example\",\"queryType\":\"service\"}]}"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        tags: ['service', 'container']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '30m'
        spanEndTimeShift: '30m'
        filterByTraceID: true
        filterBySpanID: false
        query: '{}'
      tracesToMetrics:
        datasourceUid: mimir
        tags: ['service', 'container']
        queries:
          - name: 'Request Rate'
            query: 'rate(hello_requests_total{service="$service"}[5m])'
          - name: 'Request Duration'
            query: 'histogram_quantile(0.95, rate(hello_processing_seconds_bucket{service="$service"}[5m]))'
      tracesToProfiles:
        datasourceUid: pyroscope
        tags: ['service', 'container']
        query: 'service_name="$service"'

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    uid: pyroscope
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        tags: ['service', 'container']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '30m'
        spanEndTimeShift: '30m'
        filterByTraceID: true
        filterBySpanID: false
        query: '{}'
      tracesToMetrics:
        datasourceUid: mimir
        tags: ['service', 'container']
        queries:
          - name: 'Request Rate'
            query: 'rate(hello_requests_total{service="$service"}[5m])'
          - name: 'Request Duration'
            query: 'histogram_quantile(0.95, rate(hello_processing_seconds_bucket{service="$service"}[5m]))'