server:
  port: 8080

spring:
  application:
    name: observability-example

# Actuator configuration for metrics and health endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 10s
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        hello_request_duration: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        hello_request_duration: 0.5,0.95,0.99

# Logging configuration
logging:
  level:
    me.valizadeh.observability: INFO
    org.springframework.web: INFO
    io.micrometer: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
